#
#   Author
#     - luncliff@gmail.com
#
version: 1.5.{build}

notifications:
  - provider: Email
    to:
      - luncliff@gmail.com

branches:
  except:
    - docs
    - gh-pages

image:
  - Visual Studio 2017
  - Visual Studio 2019

platform:
  - x64
  - x86

configuration:
  - Debug
  - Release

# cache:
#   - c:/tools/vcpkg/installed

environment:
  global:
    install_path: c:/install

matrix:
  allow_failures:
    # for some reason UDP test hangs forever or segfault
    # - image: Visual Studio 2017
    #   platform: x86
    - image: Visual Studio 2017
    - image: Visual Studio 2019

install:
  - ps: Write-Output $(git submodule update --init --recursive)
  - ps: if($env:PLATFORM -eq "x64"){ vcpkg install --triplet x64-windows ms-gsl }
  - ps: if($env:PLATFORM -eq "x86"){ vcpkg install --triplet x86-windows ms-gsl }

before_build:
  - ps: MSBuild.exe /version
  - ps: if($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2017"){ $env:GENERATOR="Visual Studio 15 2017" }
  - ps: if($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2019"){ $env:GENERATOR="Visual Studio 16 2019" }

build_script:
  # configure cmake and build them
  - ps: if($env:PLATFORM -eq "x64"){ cmake . -G "$env:GENERATOR" -A x64   -DCMAKE_BUILD_TYPE="$env:CONFIGURATION" -DCMAKE_INSTALL_PREFIX="$env:INSTALL_PATH" -DBUILD_SHARED_LIBS=false }
  - ps: if($env:PLATFORM -eq "x86"){ cmake . -G "$env:GENERATOR" -A Win32 -DCMAKE_BUILD_TYPE="$env:CONFIGURATION" -DCMAKE_INSTALL_PREFIX="$env:INSTALL_PATH" -DBUILD_SHARED_LIBS=false }
  - ps: cmake --build . --config $env:CONFIGURATION --target install
  - ps: cmake . -DBUILD_TESTING=ON
  - ps: cmake --build . --config $env:CONFIGURATION

test_script:
  - ps: |
      $env:PATH="$env:INSTALL_PATH/bin;$env:PATH"
      ctest --output-on-failure --timeout 600 -C $env:CONFIGURATION
